export type CourseListType = {
  name: string;
  duration: string;
  standardFee: number;
  foundingCohortFee: number;
  description: string;
  targetLearners: string[];
  coreModules: string[];
  practicalOutcome: string;
  slug: string;
  image: string;
  rating: string;
  reviews: string;
  level: string;
};

export const courseList = [
  {
    name: "viek core",
    duration: "3 Months",
    standardFee: 50000,
    foundingCohortFee: 35000,
    description:
      "Viek Core is the foundational program designed to prepare learners for the modern digital workplace. The program introduces learners to essential digital skills, workplace tools, AI, communication, collaboration, problem-solving and professional development. It is particularly suitable for learners who are unsure which digital career pathway to pursue and need a strong foundation before specializing.",
    targetLearners: [
      "Students",
      "Graduates",
      "Beginners",
      "Career starters",
      "Career switchers",
      "Individuals with limited digital experience",
    ],
    coreModules: [
      "Digital Literacy",
      "Digital Workplace Tools",
      "AI Fundamentals",
      "Digital Productivity",
      "Communication & Collaboration",
      "Critical Thinking",
      "Problem-Solving",
      "Cybersecurity Awareness",
      "Professional Ethics",
      "Career Development",
      "Digital Career Exploration",
    ],
    practicalOutcome:
      "Learners will complete a Future Skills Project and develop a personal career pathway plan.",
    slug: "viek-core",
    image: "/images/viek-core.jpeg",
    rating: "4.8",
    reviews: "300+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "VIEK CORE → VIEK SPECIALIZATION → VIEK ADVANCED",
  },
  {
    name: "ai & automation",
    duration: "3 Months",
    standardFee: 60000,
    foundingCohortFee: 40000,
    description:
      "AI & Automation is a practical program designed to help learners understand how artificial intelligence and automation can be used to improve productivity, solve problems, and streamline business and professional workflows. Rather than focusing only on AI theory, learners will work with practical AI tools and automation workflows that can be applied to education, business, administration, marketing, research, and everyday work.",
    targetLearners: [
      "Students",
      "Professionals",
      "Entrepreneurs",
      "Administrative professionals",
      "Business owners",
      "Career switchers",
      "Digital professionals",
    ],
    coreModules: [
      "AI Fundamentals",
      "Generative AI",
      "Prompting",
      "AI Research",
      "AI Productivity",
      "AI for Business",
      "Workflow Design",
      "No-Code Automation",
      "AI-Assisted Content",
      "Responsible AI",
      "AI Project Development",
    ],
    practicalOutcome:
      "Learners will design and demonstrate an AI-powered or automated workflow that solves a real problem.",
    slug: "ai-automation",
    image: "/images/automation.jpeg",
    rating: "4.9",
    reviews: "400+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "AI & Automation → VIEK SPECIALIZATION → VIEK ADVANCED",
  },
  {
    name: "data analytics",
    duration: "3-4 Months",
    standardFee: 75000,
    foundingCohortFee: 55000,
    description:
      "Data Analytics equips learners with the skills required to transform raw data into useful information for decision-making. Learners will develop practical abilities in data collection, cleaning, analysis, visualisation, and reporting while working with realistic datasets. The program is designed to help beginners progress toward entry-level data and business intelligence roles.",
    targetLearners: [
      "Students",
      "Graduates",
      "Professionals",
      "Business owners",
      "Career switchers",
      "Aspiring Data Analysts",
    ],
    coreModules: [
      "Data Fundamentals",
      "Excel",
      "Data Cleaning",
      "Basic Statistics",
      "Data Analysis",
      "SQL",
      "Data Visualization",
      "Power BI",
      "Dashboard Development",
      "Data Storytelling",
      "AI-Assisted Analytics",
    ],
    practicalOutcome:
      "Learners will create a Data Analytics Portfolio containing practical analysis, dashboards, and business recommendations.",
    slug: "data-analytics",
    image: "/images/data-analysis.jpeg",
    rating: "4.9",
    reviews: "450+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "Data Analytics → Data Engineering → Data Science",
  },
  {
    name: "cybersecurity",
    duration: "3-4 Months",
    standardFee: 80000,
    foundingCohortFee: 60000,
    description:
      "The Cybersecurity program introduces learners to the principles and practices used to protect digital systems, information, networks, and users from cyber threats. The program provides a strong foundation for learners who want to explore cybersecurity as a career while developing practical awareness of how organizations manage digital security.",
    targetLearners: [
      "Beginners",
      "Students",
      "Graduates",
      "IT beginners",
      "Career switchers",
      "Aspiring cybersecurity professionals",
    ],
    coreModules: [
      "Cybersecurity Fundamentals",
      "Cyber Threats",
      "Networking Fundamentals",
      "Operating Systems",
      "Security Principles",
      "Identity & Access",
      "Vulnerability Concepts",
      "Security Monitoring",
      "Incident Response",
      "Risk Management",
      "Cybersecurity Awareness",
    ],
    practicalOutcome:
      "Learners will complete cybersecurity exercises, case studies and a final security project.",
    slug: "cybersecurity",
    image: "/images/cyber-security.jpeg",
    rating: "4.8",
    reviews: "350+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "Cybersecurity → Network Security → Ethical Hacking",
  },
  {
    name: "software development",
    duration: "4-6 Months",
    standardFee: 100000,
    foundingCohortFee: 75000,
    description:
      "Software Development is a practical program designed to teach learners how to design, develop, and maintain digital applications and software solutions. Learners will progress from programming fundamentals to building functional projects while developing problem-solving and software development practices. AI-assisted development tools may also be incorporated to help learners understand modern software development workflows.",
    targetLearners: [
      "Beginners",
      "Students",
      "Graduates",
      "Career switchers",
      "Aspiring developers",
      "Entrepreneurs interested in technology",
    ],
    coreModules: [
      "Programming Fundamentals",
      "HTML",
      "CSS",
      "JavaScript",
      "Git & GitHub",
      "APIs",
      "Databases",
      "Debugging",
      "Software Architecture Basics",
      "AI-Assisted Development",
      "Project Development",
    ],
    practicalOutcome:
      "Learners will develop functional software projects and build a Developer Portfolio.",
    slug: "software-development",
    image: "/images/software-dev.jpeg",
    rating: "4.9",
    reviews: "500+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "Software Development → Web Development → Full Stack Development",
  },
  {
    name: "cloud engineering",
    duration: "3-4 Months",
    standardFee: 90000,
    foundingCohortFee: 65000,
    description:
      "Cloud Engineering introduces learners to the technologies and practices used to build, deploy and manage applications and infrastructure in cloud environments. The program provides foundational knowledge of cloud infrastructure, networking, storage, security and deployment. It also introduces learners to containers and DevOps concepts as a pathway toward more advanced cloud careers.",
    targetLearners: [
      "IT beginners",
      "Students",
      "Graduates",
      "Aspiring cloud engineers",
      "Software developers",
      "IT professionals",
    ],
    coreModules: [
      "Cloud Computing Fundamentals",
      "Cloud Infrastructure",
      "Virtual Machines",
      "Cloud Networking",
      "Cloud Storage",
      "Identity & Access",
      "Cloud Security",
      "Deployment",
      "Containers",
      "DevOps Fundamentals",
      "Cloud Projects",
    ],
    practicalOutcome:
      "Learners will complete practical cloud deployment and infrastructure projects.",
    slug: "cloud-engineering",
    image: "/images/cloud-engineering.jpeg",
    rating: "4.8",
    reviews: "400+",
    level: "Intermediate",
    // careerPathway:
    //   "Cloud Engineering → Cloud Architecture → DevOps Engineering",
  },
  {
    name: "product design",
    duration: "3-4 Months",
    standardFee: 75000,
    foundingCohortFee: 55000,
    description:
      "Product Design teaches learners how to research user needs, identify problems and design digital products that provide useful and accessible experiences. The program combines UX research, UI design, prototyping and product thinking. Learners will work on realistic design challenges and develop case studies for their portfolios.",
    targetLearners: [
      "Beginners",
      "Creative professionals",
      "Students",
      "Graduates",
      "Aspiring UI/UX designers",
      "Career switchers",
    ],
    coreModules: [
      "Design Thinking",
      "User Research",
      "UX Fundamentals",
      "UI Design",
      "Wire framing",
      "Prototyping",
      "Figma",
      "Design Systems",
      "Accessibility",
      "AI-Assisted Design",
      "Portfolio Development",
    ],
    practicalOutcome:
      "Learners will develop multiple Product Design Case Studies for their professional portfolio.",
    slug: "product-design",
    image: "/images/uiux.jpeg",
    rating: "4.9",
    reviews: "450+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "Product Design → UX Design → UI/UX Design",
  },
  {
    name: "digital marketing",
    duration: "3 Months",
    standardFee: 60000,
    foundingCohortFee: 45000,
    description:
      "Digital Marketing equips learners with practical skills for helping organizations and businesses build an online presence, attract audiences and grow their digital channels. The program combines marketing strategy, content, social media, customer research, analytics and AI-supported marketing.",
    targetLearners: [
      "Students",
      "Entrepreneurs",
      "Business owners",
      "Marketing beginners",
      "Graduates",
      "Freelancers",
      "Career switchers",
    ],
    coreModules: [
      "Marketing Fundamentals",
      "Digital Strategy",
      "Audience Research",
      "Content Strategy",
      "Social Media Marketing",
      "SEO Fundamentals",
      "Email Marketing",
      "Marketing Analytics",
      "Campaign Development",
      "AI for Marketing",
    ],
    practicalOutcome:
      "Learners will develop a Digital Marketing Campaign Portfolio.",
    slug: "digital-marketing",
    image: "/images/digital_marketing.jpeg",
    rating: "4.8",
    reviews: "400+",
    level: "Beginner",
    // careerPathway:
    //   "Digital Marketing → Social Media Marketing → Digital Marketing Specialist",
  },
  {
    name: "project management",
    duration: "3 Months",
    standardFee: 60000,
    foundingCohortFee: 45000,
    description:
      "Project Management prepares learners to plan, coordinate, monitor and successfully deliver projects. The programme focuses on practical project management rather than theory alone. Learners will work with project planning tools and methodologies used by modern teams.",
    targetLearners: [
      "Students",
      "Graduates",
      "Professionals",
      "Project coordinators",
      "Administrative professionals",
      "Aspiring project managers",
      "Career switchers",
    ],
    coreModules: [
      "Project Management Fundamentals",
      "Project Planning",
      "Scope Management",
      "Scheduling",
      "Risk Management",
      "Stakeholder Management",
      "Agile",
      "Scrum",
      "Kanban",
      "Project Management Tools",
      "AI for Project Management",
    ],
    practicalOutcome:
      "Learners will create and manage a complete project plan from initiation to closure.",
    slug: "project-management",
    image: "/images/project-management.jpeg",
    rating: "4.9",
    reviews: "450+",
    level: "Beginner to Advanced",
    // careerPathway:
    //   "Project Management → Agile Project Management → Project Management Professional",
  },
  {
    name: "digital operations",
    duration: "3 Months",
    standardFee: 60000,
    foundingCohortFee: 45000,
    description:
      "Digital Operations prepares learners to support and coordinate modern digital teams, workflows, and business processes. The programme combines digital productivity, operations management, documentation, workflow optimization, collaboration tools, AI and automation. It provides a pathway for individuals interested in remote operations and business support roles.",
    targetLearners: [
      "Administrative professionals",
      "Virtual assistants",
      "Graduates",
      "Students",
      "Operations assistants",
      "Entrepreneurs",
      "Career switchers",
    ],
    coreModules: [
      "Digital Workplace Tools",
      "Documentation",
      "Workflow Management",
      "Process Improvement",
      "CRM Fundamentals",
      "Team Collaboration",
      "Digital Systems",
      "AI Productivity",
      "Automation",
      "Operations Reporting",
    ],
    practicalOutcome:
      "Learners will develop and document a Digital Operations Workflow for a simulated organization.",
    slug: "digital-operations",
    image: "/images/digital-operations.jpeg",
    rating: "4.8",
    reviews: "400+",
    level: "Beginner",
    // careerPathway:
    //   "Digital Operations → Remote Team Management → Operations Management",
  },
  {
    name: "virtual assistant",
    duration: "4 Weeks",
    standardFee: 20000,
    foundingCohortFee: 15000,
    description:
      "The Virtual Assistant program is a short, practical program designed to introduce learners to the skills required to provide remote administrative and digital support. Learners will develop practical skills in communication, research, scheduling, documentation, digital collaboration, and productivity tools. The programme is designed as an accessible entry point into remote work and can serve as a pathway into Digital Operations.",
    targetLearners: [
      "Beginners",
      "Students",
      "Graduates",
      "Job seekers",
      "Remote work beginners",
      "Aspiring virtual assistants",
    ],
    coreModules: [
      "Introduction to Virtual Assistance",
      "Professional Communication",
      "Email Management",
      "Calendar Management",
      "Online Research",
      "Documentation",
      "Scheduling",
      "Digital Collaboration",
      "Productivity Tools",
      "AI for Virtual Assistance",
      "Client Management",
    ],
    practicalOutcome:
      "Learners will complete simulated client tasks and develop a Virtual Assistant Starter Portfolio.",
    // careerPathway:
    //   "Virtual Assistant → Digital Operations → Project Coordination",
    slug: "virtual-assistant",
    image: "/images/virtual-assistant.jpeg",
    rating: "4.7",
    reviews: "300+",
    level: "Beginner",
  },
  {
    name: "graphic design & content",
    duration: "3 Months",
    standardFee: 50000,
    foundingCohortFee: 35000,
    description:
      "Graphic Design & Content teaches learners how to communicate ideas visually and create digital content for businesses, brands and online platforms. The program combines design fundamentals, branding, content creation and modern AI-assisted creative workflows.",
    targetLearners: [
      "Beginners",
      "Students",
      "Entrepreneurs",
      "Content creators",
      "Aspiring designers",
      "Marketing professionals",
    ],
    coreModules: [
      "Design Fundamentals",
      "Branding",
      "Typography",
      "Layout",
      "Colour & Visual Communication",
      "Social Media Design",
      "Content Creation",
      "Canva",
      "Visual Storytelling",
      "AI-Assisted Design",
      "Portfolio Development",
    ],
    practicalOutcome:
      "Learners will develop a Creative Portfolio containing branding, social media and content projects.",
    slug: "graphic-design-content",
    image: "/images/graphics-design.jpeg",
    rating: "4.8",
    reviews: "350+",
    level: "Beginner",
    // careerPathway:
    //   "Graphic Design & Content → Visual Communication → Creative Direction",
  },
];
